# Generated by Django 5.1.7 on 2025-04-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Alta'), (2, 'Media'), (3, 'Baja')], default=2),
        ),
    ]
